### ISSUE TITLE
Mismatched between RubyGem name and installation instructions 

### ISSUE THREAD

**Issue by ltfschoen** [scarsam/crypto_market#1]
It appears you've deployed this library to RubyGems as crypto-market (using a dash) but your installation instructions suggest installation with `gem install crypto_market` (using an underscore), which causes issues for end users such as:
```
ERROR:  Could not find a valid gem 'crypto_market' (>= 0) in any repository
ERROR:  Possible alternatives: crypto-market
```

**Comment by scarsam** [comment]
Thanks for reporting @ltfschoen, I updated the version with a fix to this problem!
https://github.com/scarsam/crypto_market/commit/64041cc0f3452e361fed672f3565768d493ca51c
